services:
  neo4j:
    image: neo4j:4.0
    volumes:
        - ./neo4j/logs:/logs
        - ./neo4j/config:/config
        - ./neo4j/data:/data
        - ./neo4j/plugins:/plugins
    environment:
        - NEO4J_AUTH=neo4j/12345678
        - NEO4J_PLUGINS='["apoc"]'
        - NEO4JLABS_PLUGINS='["apoc"]'
        - NEO4J_apoc_export_file_enabled=true
        - NEO4J_apoc_import_file_enabled=true
        - NEO4J_apoc_import_file_use__neo4j__config=true
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always